### ISSUE TITLE
Phylip Installaion

### ISSUE THREAD

**Issue by vivekruhela** [matsengrp/gctree#123]
Can anyone suggest to me how to install Phylip. I tried conda (as suggested in documentation) but it's not working (error screenshot shown below).
![Phylip error](https://github.com/matsengrp/gctree/assets/13174913/267d98f8-3733-46e9-b9ae-2cee8af84522)

I also tried to build it from source in Linux (both 3.697 nd 3.698 version), it is also not working (error screenshot shown below)
![phylip error2](https://github.com/matsengrp/gctree/assets/13174913/91f31934-8c3f-4d58-a991-17bd57a80351)

I really appreciate any help. Thanks

**Comment by willdumm** [comment]
Hi Vivek,

I've had luck following the build instructions on Linux, although I'm not sure what's going wrong in your case. Luckily it shouldn't be necessary to build from source though, since there are pre-built executables available on the PHYLIP website. They're very difficult to find, but they've worked for me on Mac and Linux (I don't use windows, but there are windows executables available too)

Here's the downloads page where you'll find those: https://phylipweb.github.io/phylip/getme-new1.html
You should be able to just unzip the archive wherever you like and either link the binary somewhere in your path or just run it with a full file path where it is.

**Comment by vivekruhela** [comment]
Thanks for your reply. As per gctree documentation,  I need to pre-process fasta files using deduplicate module. But in the available executables, I didn't find a deduplicate executable which is the reason why I am trying to build it from source. Let me know if I have missed something. Thanks.

**Comment by willdumm** [comment]
Ah I see. The `deduplicate` tool is part of gctree, and like the cli tools `gctree` and `mkconfig`, should automatically be available in any environment in which gctree is installed with pip or conda.

**Comment by vivekruhela** [comment]
Thanks. Problem solved.
