### ISSUE TITLE
Various comments/suggestions

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/gctree#84]
- I think the phrasing here says you don't have to run the separate phylip install command below, but afaict you still need to run it https://matsengrp.github.io/gctree/install.html#anaconda-install
  - i don't see a sequence named '17' [here](https://matsengrp.github.io/gctree/quickstart.html#input-data)?
  -  --idmapfile says it's for isotype mapping, but I found it extremely useful even without isotype mapping (didn't figure any other way to get back to my sequence names) so maybe worth changing the help msg? 
  - i don't understand the first part of the --idlabel help (`--idlabel             flag for labeling the sequence ids of the nodes in the output tree images, also write associated fasta alignment if ``True`` (default: False)`, is it saying that otherwise the nodes are not labelled? In either case it was the only way I could figure out to get the inferred ancestral sequences without parsing phylip output horrendousness, so if that's true maybe worth emphasizing that?
  - I don't understand the details of this traceback message, but it seems to get triggered a lot, e.g. if you try rerunning without perfectly nuking everything so phylip doesn't get confused. So maybe it could be more informative that that's what's happening since it'll probably take people a while to figure out that's what's actually wrong?
```#  - this traceback should have a more informative message since it seems to get triggered by almost anything going wrong
            Traceback (most recent call last):
              File "/home/dralph/miniconda3/envs/gctree/bin/gctree", line 10, in <module>
                sys.exit(main())
              File "/home/dralph/miniconda3/envs/gctree/lib/python3.9/site-packages/gctree/cli.py", line 735, in main
                args.func(args)
              File "/home/dralph/miniconda3/envs/gctree/lib/python3.9/site-packages/gctree/cli.py", line 169, in infer
                *pp.parse_outfile(args.infiles[0], args.infiles[1], args.root)
              File "/home/dralph/miniconda3/envs/gctree/lib/python3.9/site-packages/gctree/phylip_parse.py", line 142, in parse_outfile
                sequence_counts = {sequences[name]: count for name, count in counts.items()}
              File "/home/dralph/miniconda3/envs/gctree/lib/python3.9/site-packages/gctree/phylip_parse.py", line 142, in <dictcomp>
                sequence_counts = {sequences[name]: count for name, count in counts.items()}
            KeyError: 'naive'
```

**Comment by willdumm** [comment]
* fixed this morning. For some reason I had thought I'd made PHYLIP a dependency, but now I think it's best that it isn't, since gctree does not strictly depend on PHYLIP to run (it just needs its outputs) and a user might want to use PHYLIP compiled on their system, for example if the bioconda recipe doesn't work on their machine.
* sorry, we removed the ability to use abundances as fasta names, but missed this reference when we were updating the docs
* Both `deduplicate` and `gctree infer` accept the argument `--idmapfile`. For `deduplicate`, this argument provides a filename to write the idmap to, and for `gctree infer`, the argument specifies a filename from which to read this data. I _think_ the help strings are correct, but I've tried to clarify the one for `gctree infer` to emphasize that it is for reading in an _existing_ file.
* Hopefully it's better now. You're right, this is the easiest way to get a map of ancestral nodes to sequences. You could also load the pickled tree and read the sequences directly from the nodes with the gctree/ete3 api.
* I added a couple of error messages!

This is all done in #85.

**Comment by psathyrella** [comment]
wooooooo, thank you!
